### ISSUE TITLE
capture video with ffmpeg

### ISSUE THREAD

**Issue by mattrei** [xqms/xtion#14]
Hi,

I have tried your module and it works well with Gnome's *Cheese* webcam application (except the depth device of course)
However if I want to capture the video via *ffmpeg* using ```ffmpeg -f v4l2 -i /dev/video1 output.mkv``` 
I get the following error ```[video4linux2,v4l2 @ 0x5565ccb28de0] ioctl(VIDIOC_G_INPUT): Inappropriate ioctl for device
/dev/video2: Inappropriate ioctl for device```

The error appears with the color *and* depth device.

Thanks,
Matthias

**Comment by xqms** [comment]
Thanks for your report!

That seems to be a bug in ffmpeg (it should not require devices to handle input channel selection). Nevertheless, I implemented the `VIDIOC_*_INPUT` ioctls in the `feature/vidioc_g_input` branch. Could you try that out? I don't have an xtion device on hand right now.

Otherwise, I can probably try it tomorrow myself.

**Comment by mattrei** [comment]
wow that was quick :) works like a charm with the color device (not with  the depth device though because the driver does not seem to support it, see:
```
[video4linux2,v4l2 @ 0x55ee3e7e0ea0] Cannot find a proper format for codec 'none' (id 0), pixel format 'none' (id -1)
Assertion *codec_id != AV_CODEC_ID_NONE failed at libavdevice/v4l2.c:821
```

However how can I capture the depth stream? With _cheese_ and _ffmpeg_ its not possible. I want to have a result like this video: http://threejs.org/examples/textures/kinect.webm

Thanks for your work.

**Comment by xqms** [comment]
Here is another test branch for you: `feature/ffmpeg_depth`. It reports true 16-bit grayscale output, which `ffmpeg` is able to handle. Something like this records data:

```
ffmpeg -f v4l2 -i /dev/xtion_1210170052_depth output.mkv
```

Since the data is in millimeters, the video is going to be quite dark (white = 65m distance).

```
ffmpeg -f v4l2 -i /dev/xtion_1210170052_depth -vf curves=all='0.1/1.0' output.mkv
```
makes the data visible, but now you get rounding effects because the distance is first scaled to 8 bits and then scaled up.

Seems to me that `ffmpeg` is not *quite* up to the job yet. Maybe you discover some other flag that enables scaling *before* the conversion to 8 bit...

**Comment by xqms** [comment]
For a quick hack, you can record raw 16-bit png frames, scale them with ImageMagick, and stitch a video together:

```
# Record
ffmpeg -f v4l2 -i /dev/xtion_1210170052_depth -f image2 frame-%03d.png

# Scale by 50
for i in frame-*; do convert $i -fx 'u*50' $i; done

# Stitch
ffmpeg -framerate 30 -i blub-%03d.png output.mkv
```

I'll have to think about merging the `feature/ffmpeg_depth` branch, I'm not sure about that yet.

**Comment by mattrei** [comment]
Thanks,
for me the results are totally fine,  because in my project I am not using ffmpeg to record a video however record video/pictures within Ruby (via the `hornetseye-v4l2` library) and there the results look like those I get from OpenNi.

So if you ask me the branch works fine.

**Comment by xqms** [comment]
Merged. Thanks for your feedback :-)
