### ISSUE TITLE
Depth stream in Browsers via MediaStream API

### ISSUE THREAD

**Issue by mattrei** [xqms/xtion#18]
Hi,

I wanna ask you, if it may be possible to stream the depth stream into Chrome/Firefox via the MediaStream API. Chrome and Firefox just allow me to select the Color device not the Depth device for its input (I am not sure on which conditions the browser are blocking the depth device).

For my visualization project I would rely on the Depth stream, so may there be any possibilities to "fix" this issue?

Thx for reading,
Best

**Comment by xqms** [comment]
Hi,

this is probably because this driver advertises a 16 bit grayscale stream, which the browsers cannot handle (not verified). Since squeezing the data into 8 bit grayscale is stupid in most situations due to the precision loss, I'm not going to change that.

Theoretically, it would be possible to add a second output format that could be chosen by the userspace application. I would accept a pull request in that direction, but I'm not going to work on it myself.

For your project, I would recommend using software that can actually handle 16-bit grayscale streams, such as `ffmpeg` / `ffserver`.

**Comment by xqms** [comment]
Follow-up: Firefox only supports color streams: https://dxr.mozilla.org/mozilla-beta/rev/958cee08361af9ed370be06695973bcda3d3aa46/media/webrtc/trunk/webrtc/modules/video_capture/linux/video_capture_linux.cc#165

As I said above, you should be able to get something working over ffserver, which could convert the 16-bit grayscale from xtion to a color stream. The browser could connect to that using the MediaStream PeerConnection API.

It seems that 16-bit depth capture support is worked upon in W3C, though: https://www.w3.org/TR/mediacapture-depth/

I'm closing the ticket as there is nothing more I can do from the driver side.

**Comment by mattrei** [comment]
Thanks for you extended research on the topic. Yes the Depth MediaCapture API looks indeed promising and hopefully the browser vendors will implement it soon.

Thx for the tip with the ffmpeg server. Will look into that as well.
